package com.example.atozchatlibrary.atozpay.model

import com.example.atozchatlibrary.atozpay.utilities.Constants.Companion.CHAT_DOC_FIELD_NAME_AUTO_GENERATED
import com.example.atozchatlibrary.atozpay.utilities.Constants.Companion.CHAT_DOC_FIELD_NAME_CHAT_BODY
import com.example.atozchatlibrary.atozpay.utilities.Constants.Companion.CHAT_DOC_FIELD_NAME_SENDER_ID
import com.example.atozchatlibrary.atozpay.utilities.Constants.Companion.CHAT_DOC_FIELD_NAME_SENDER_NAME
import com.example.atozchatlibrary.atozpay.utilities.Constants.Companion.CHAT_DOC_FIELD_NAME_TIME_SENT
import com.google.firebase.Timestamp
import com.google.firebase.firestore.Exclude
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.ServerTimestamp
import java.util.*

data class Chat(
    /**
     * to determine the chat type whether incoming or outgoing chat
     * 1 for outgoing chat
     * 2 for incoming chat
     */
    val type: Int? = 0,

    val senderId: String? = null,
    val senderName: String? = null,
    val body: String? = null,
    val isAutoGenerated: Boolean = false,
    @ServerTimestamp
    val timeSent: Timestamp? = null
) {
    @Exclude
    fun toMap(): Map<String, Any> {
        val result = HashMap<String, Any>()
        result[CHAT_DOC_FIELD_NAME_CHAT_BODY] = body!!
        result[CHAT_DOC_FIELD_NAME_SENDER_ID] = senderId!!
        result[CHAT_DOC_FIELD_NAME_SENDER_NAME] = senderName!!
        result[CHAT_DOC_FIELD_NAME_AUTO_GENERATED] = isAutoGenerated
        result[CHAT_DOC_FIELD_NAME_TIME_SENT] = FieldValue.serverTimestamp()
        return result
    }
}